### ISSUE TITLE
Training set

### ISSUE THREAD

**Issue by Mayer123** [zengzp0912/SEAME-dev-set#1]
Hi there, 

Great work! I have one question about the dataset. I assume you used both phase I and phase II right? (Phase II mostly covers Phase I but there are 7 files that only appear in Phase I, please correct me if I am wrong) What is the number of utterances and number of hours for training, dev-man and dev-sge set?  
 In fact, I am also working on end-to-end models on SEAME dataset. I am wondering if you can also share the training set data files? I saw that the transcripts you posted here are much cleaner than what I got from LDC. It would really help a lot and make it easier to compare with your results. Please let me know if you have any questions or concerns. 

Thank you!

**Comment by zengzp0912** [comment]
> Hi there,
> 
> Great work! I have one question about the dataset. I assume you used both phase I and phase II right? (Phase II mostly covers Phase I but there are 7 files that only appear in Phase I, please correct me if I am wrong) What is the number of utterances and number of hours for training, dev-man and dev-sge set?
> In fact, I am also working on end-to-end models on SEAME dataset. I am wondering if you can also share the training set data files? I saw that the transcripts you posted here are much cleaner than what I got from LDC. It would really help a lot and make it easier to compare with your results. Please let me know if you have any questions or concerns.
> 
> Thank you!

Because of some LDC License issues, I can't share training data in the community. We are plan to summit the detail train and dev set in LDC.
